# Generated by Django 4.2.20 on 2025-05-04 09:32

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_apikey_delete_activeorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="api_key",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="api_secret",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
